### ISSUE TITLE
How to bind the receiver

### ISSUE THREAD

**Issue by norulers** [ExpressLRS/Handset#3]
HI，
I made a handset, how to work with my (targets=DIY_2400_RX_ESP8285_SX1280_via_UART) receiver connection ？
Edit  platformio.ini   -D MY_UID=0x17,0x13,0x31,0x19,0x23,0xEB   ?

**Comment by JBKingdon** [comment]
Yes, the UID from normal elrs is printed near the start of the build, so copy those values into your handset Ini to match.

**Comment by JBKingdon** [comment]
Jump in the elrs discord #handset if you have questions 😃

**Comment by JBKingdon** [comment]
The handset firmware has to match a particular release of the Rx firmware. The handset code in the master branch has a define to set the level, currently tested against elrs v1 rc3
https://github.com/ExpressLRS/Handset/blob/2ebdbcb9a97226b92c6d1f1d9e7b86cda5ec3f63/src/config.h#L18

**Comment by norulers** [comment]
ExpressLRS-1.0.0-RC3

targets=DIY_2400_RX_ESP8285_SX1280_via_WIFI

``Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 10,183,12,124,56,3
Installing GitPythonRequirement already satisfied: GitPython in c:\users\norulers\.platformio\penv\lib\site-packages (3.1.17)


[env:sipeed-longan-nano]
platform = gd32v
; platform = https://github.com/sipeed/platform-gd32v.git
board = sipeed-longan-nano
framework = gd32vf103-sdk
build_unflags = -Os
build_flags = -O2
    -D MY_UID=10,183,12,124,56,3
    ; -D USE_FLRC

upload_protocol = dfu

; upload_protocol = serial
; upload_port = /dev/ttyUSB1
upload_speed = 460800

debug_tool = sipeed-rv-debugger
; upload_protocol = sipeed-rv-debugger

monitor_speed = 460800
; monitor_port = /dev/ttyUSB1

The receiver cannot be connected

**Comment by JBKingdon** [comment]
Hey @norulers - sorry I must have missed your last update. Did you get things working?

**Comment by JBKingdon** [comment]
Hi @norulers , how are things going? Do we still need this issue or shall I close it now?

**Comment by norulers** [comment]
After updating the firmware, it can be used normally.
